version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
            - ./application:/data
            - ./auth.json:/root/.composer/auth.json
        user: "${DOCKER_UIDGID}"

    db:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        env_file:
            - ./local.env

    app:
        build: ./
        volumes_from:
            - data
        ports:
            - "8090:80"
        depends_on:
            - db
        env_file:
            - ./local.env
        environment:
            LDAP_BASE_DN: dc=acme,dc=org
            LDAP_ADMIN_USERNAME: cn=Manager,dc=acme,dc=org
            LDAP_ADMIN_PASSWORD: admin
            LDAP_DOMAIN_CONTROLLERS: ldap
            LDAP_USE_SSL: "false"
            LDAP_USE_TLS: "false"

    cron:
        build: ./
        volumes_from:
            - data
        depends_on:
            - db
        env_file:
            - ./local.env
        command: ["/data/run-cron.sh"]

    appfortests:
        build: ./
        volumes_from:
            - data
        ports:
            - "8082:80"
        depends_on:
            - appfortestsdb
        environment:
            API_ACCESS_KEYS: api-test-NOTASECRET
            APP_ENV: test
            EMAIL_SERVICE_accessToken: dummy
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: dummy
            EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
            IDP_NAME: test
            LDAP_BASE_DN: dc=acme,dc=org
            LDAP_ADMIN_USERNAME: cn=Manager,dc=acme,dc=org
            LDAP_ADMIN_PASSWORD: admin
            LDAP_DOMAIN_CONTROLLERS: ldap
            LDAP_USE_SSL: "false"
            LDAP_USE_TLS: "false"
            MIGRATE_PW_FROM_LDAP: "true"
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_HOST: appfortestsdb
            MYSQL_DATABASE: appfortests
            MYSQL_USER: appfortests
            MYSQL_PASSWORD: appfortests
            MIGRATE_PW_FROM_LDAP: "true"
            PASSWORD_FORGOT_URL: https://www.example.com/forgot
            SUPPORT_EMAIL: support@example.com

    appfortestsdb:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_DATABASE: appfortests
            MYSQL_USER: appfortests
            MYSQL_PASSWORD: appfortests

    cli:
        image: silintl/php7:latest
        volumes_from:
            - data
        working_dir: /data
        env_file:
            - ./local.env
        command: ["true"]

    ldap:
        build:
            context: ./development/ldap
            dockerfile: Dockerfile
        ports:
            - "389"
        env_file:
            - ./local.env
        working_dir: /data
        environment:
            DEBUG_LEVEL: 320

    ldapload:
        build:
            context: ./development/ldap
            dockerfile: Dockerfile
        working_dir: /data
        env_file:
            - ./local.env
        environment:
            DEBUG_LEVEL: 320
        links:
            - ldap
        volumes:
            - ./development/ldap/fakepeople.ldif:/root/fakepeople.ldif
            - ./development/ldap/fakerep.ldif:/root/fakerep.ldif
        command: bash -c "sleep 10 && /data/load_ldap.sh"

    test:
        image: silintl/php7:latest
        volumes_from:
            - data
        working_dir: /data
        depends_on:
            - appfortests
        environment:
            TEST_SERVER_HOSTNAME: appfortests
            API_ACCESS_KEYS: api-test-NOTASECRET
            APP_ENV: test
            EMAIL_SERVICE_accessToken: dummy
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: dummy
            HELP_CENTER_URL: https://www.example.com/help
            IDP_DISPLAY_NAME: Test
            IDP_NAME: test
            LDAP_BASE_DN: dc=acme,dc=org
            LDAP_ADMIN_USERNAME: cn=Manager,dc=acme,dc=org
            LDAP_ADMIN_PASSWORD: admin
            LDAP_DOMAIN_CONTROLLERS: ldap
            LDAP_USE_SSL: "false"
            LDAP_USE_TLS: "false"
            MYSQL_DATABASE: appfortests
            MYSQL_HOST: appfortestsdb
            MYSQL_PASSWORD: appfortests
            MYSQL_USER: appfortests
            PASSWORD_FORGOT_URL: https://www.example.com/forgot
            PASSWORD_PROFILE_URL: https://www.example.com/profile
            SUPPORT_EMAIL: support@example.com
        command: ./run-tests.sh
        # running isolated tests
        # docker-compose run --rm test vendor/bin/behat --stop-on-failure features/user.feature
        # docker-compose run --rm test vendor/bin/behat --stop-on-failure features/user.feature:306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8091:80"
        depends_on:
            - db
        env_file:
            - ./local.env
        environment:
            PMA_HOST: db
            PMA_USER: user
            PMA_PASSWORD: pass

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.39.0/24
              gateway: 10.20.39.1

