version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
            - ./application:/data
            - ./auth.json:/root/.composer/auth.json
        user: "${DOCKER_UIDGID}"

    db:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        env_file:
            - ./local.env

    app:
        build: ./
        volumes_from:
            - data
        ports:
            - "8080:80"
        depends_on:
            - db
        env_file:
            - ./local.env

    cli:
        image: silintl/php7:latest
        volumes_from:
            - data
        working_dir: /data
        env_file:
            - ./local.env
        command: ["true"]

    ldap:
        build:
            context: ./development/ldap
            dockerfile: Dockerfile
        ports:
            - "389"
        env_file:
            - ./local.env
        working_dir: /data
        environment:
            DEBUG_LEVEL: 320

    ldapload:
        build:
            context: ./development/ldap
            dockerfile: Dockerfile
        working_dir: /data
        env_file:
            - ./local.env
        environment:
            DEBUG_LEVEL: 320
        links:
            - ldap
        volumes:
            - ./development/ldap/fakepeople.ldif:/root/fakepeople.ldif
            - ./development/ldap/fakerep.ldif:/root/fakerep.ldif
        command: bash -c "sleep 10 && /data/load_ldap.sh"

    test:
        image: silintl/php7:latest
        volumes_from:
            - data
        working_dir: /data
        depends_on:
            - app
        env_file:
            - ./local.env
        environment:
            TEST_SERVER_HOSTNAME: app
            APP_ENV: test
        command: vendor/bin/behat --stop-on-failure
        # running isolated tests
        # docker-compose run --rm test vendor/bin/behat --stop-on-failure features/user.feature
        # docker-compose run --rm test vendor/bin/behat --stop-on-failure features/user.feature:306

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.39.0/24
              gateway: 10.20.39.1

